//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RosLecture
{
    [Serializable]
    public class TaskResultMsg : Message
    {
        public const string k_RosMessageName = "ros_lecture_msgs/TaskResult";
        public override string RosMessageName => k_RosMessageName;

        //  Define the result
        public bool done;

        public TaskResultMsg()
        {
            this.done = false;
        }

        public TaskResultMsg(bool done)
        {
            this.done = done;
        }

        public static TaskResultMsg Deserialize(MessageDeserializer deserializer) => new TaskResultMsg(deserializer);

        private TaskResultMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.done);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.done);
        }

        public override string ToString()
        {
            return "TaskResultMsg: " +
            "\ndone: " + done.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
