//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.RosLecture
{
    [Serializable]
    public class TaskFeedbackMsg : Message
    {
        public const string k_RosMessageName = "ros_lecture_msgs/TaskFeedback";
        public override string RosMessageName => k_RosMessageName;

        //  Define a feedback message
        public float rate;

        public TaskFeedbackMsg()
        {
            this.rate = 0.0f;
        }

        public TaskFeedbackMsg(float rate)
        {
            this.rate = rate;
        }

        public static TaskFeedbackMsg Deserialize(MessageDeserializer deserializer) => new TaskFeedbackMsg(deserializer);

        private TaskFeedbackMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.rate);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.rate);
        }

        public override string ToString()
        {
            return "TaskFeedbackMsg: " +
            "\nrate: " + rate.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
